'use server';

import { GoogleGenerativeAI } from "@google/generative-ai";

type AnswerResult = {
  title: string;
  description: string;
  text: string;
  source: string;
  image: string | null;
  url: string | null;
};

function trySolveBasicMath(question: string): string | null {
  const cleaned = question
    .toLowerCase()
    .replace(/what is|calculate|solve|equals|=|\?/g, "")
    .replace(/\s+/g, "");

  if (!cleaned || /[^0-9+\-*/().]/.test(cleaned)) return null;
  if (/[+\-*/]{2,}/.test(cleaned.replace(/^\-/, ""))) return null;

  try {
    const result = Function(`"use strict"; return (${cleaned})`)();
    if (typeof result !== "number" || !Number.isFinite(result)) return null;
    return `${cleaned} = ${result}`;
  } catch {
    return null;
  }
}

async function generateWithGemini(question: string): Promise<AnswerResult | null> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return null;

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const prompt = `
You are a helpful AI tutor for kids.
Answer the user's question clearly and correctly.
Use simple language.
If the question is math, give the final answer first, then 1-2 short explanation lines.
Keep your response under 120 words.

Question: ${question}
`;

    const result = await model.generateContent(prompt);
    const text = result.response.text()?.trim();
    if (!text) return null;

    return {
      title: "AI Tutor Answer",
      description: "Generated by Gemini",
      text,
      source: "Gemini",
      image: null,
      url: null,
    };
  } catch (error) {
    console.error("Gemini Error:", error);
    return null;
  }
}

async function generateFromSearch(question: string): Promise<AnswerResult | null> {
  const topic = question
    .replace(/^(who|what|where|when|why|how)\s(is|are|was|were|do|does|did|can|could|should|would)\s/i, "")
    .replace(/^(the|a|an)\s/i, "")
    .trim();

  if (!topic) return null;

  const wikiSearchUrl = `https://en.wikipedia.org/w/api.php?action=opensearch&search=${encodeURIComponent(topic)}&limit=1&format=json`;
  const searchResp = await fetch(wikiSearchUrl);
  const searchData = await searchResp.json();

  let bestTitle = topic;
  if (searchData[1] && searchData[1][0]) {
    bestTitle = searchData[1][0];
  }

  const summaryUrl = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(bestTitle)}`;
  const summaryResp = await fetch(summaryUrl);

  if (summaryResp.ok) {
    const data = await summaryResp.json();
    if (data.extract) {
      return {
        title: data.title,
        description: data.description || "Encyclopedia Entry",
        text: data.extract,
        source: "Wikipedia",
        image: data.thumbnail?.source || null,
        url: data.content_urls?.desktop?.page || `https://en.wikipedia.org/wiki/${encodeURIComponent(bestTitle)}`,
      };
    }
  }

  const ddgUrl = `https://api.duckduckgo.com/?q=${encodeURIComponent(topic)}&format=json&no_html=1&skip_disambig=1`;
  const ddgResp = await fetch(ddgUrl);
  if (ddgResp.ok) {
    const ddgData = await ddgResp.json();
    if (ddgData.AbstractText) {
      return {
        title: ddgData.Heading || topic,
        description: "Instant Answer",
        text: ddgData.AbstractText,
        source: "DuckDuckGo",
        image: ddgData.Image || null,
        url: ddgData.AbstractURL || null,
      };
    }
  }

  return null;
}

export async function generateAnswer(question: string): Promise<AnswerResult> {
  const trimmed = question.trim();
  if (!trimmed) {
    return {
      title: "No question",
      description: "Input required",
      text: "Please ask a question.",
      source: "System",
      image: null,
      url: null,
    };
  }

  try {
    const aiAnswer = await generateWithGemini(trimmed);
    if (aiAnswer) return aiAnswer;

    const mathAnswer = trySolveBasicMath(trimmed);
    if (mathAnswer) {
      return {
        title: "Math Answer",
        description: "Local calculator fallback",
        text: `The answer is ${mathAnswer.split("=").at(-1)?.trim()}.`,
        source: "Local Solver",
        image: null,
        url: null,
      };
    }

    const searchAnswer = await generateFromSearch(trimmed);
    if (searchAnswer) return searchAnswer;

    return {
      title: "No direct result",
      description: "Fallback response",
      text: "I could not find a reliable answer. Please try rephrasing your question.",
      source: "System",
      image: null,
      url: null,
    };
  } catch (error) {
    console.error("Answer generation error:", error);
    return {
      title: "Error",
      description: "System error",
      text: "I had trouble getting the answer. Please try again.",
      source: "System",
      image: null,
      url: null,
    };
  }
}
